# Generated by Django 3.2.6 on 2021-08-20 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loging',
            name='creatime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 16, 12, 51, 118004), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='loging',
            name='mse',
            field=models.CharField(default='默认内容', max_length=200, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='loging',
            name='state',
            field=models.CharField(default='默认状态', max_length=200, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='loging',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='loging',
            name='users',
            field=models.CharField(default='默认用户名', max_length=200, verbose_name='用户名/token'),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='Recentime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 16, 12, 51, 55519), verbose_name='最近登录时间'),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='balance',
            field=models.IntegerField(default=10, verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='creatime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 16, 12, 51, 55519), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='isBanned',
            field=models.BooleanField(default=False, verbose_name='是否封禁'),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='purchasetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 16, 12, 51, 55519), verbose_name='购买时间'),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='remark',
            field=models.CharField(default='备注', max_length=200, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='timelength',
            field=models.IntegerField(default=3600, verbose_name='时长(秒)'),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='token',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='令牌'),
        ),
        migrations.AlterField(
            model_name='user_admin',
            name='Recentime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 16, 12, 51, 118004), verbose_name='最近登录时间'),
        ),
        migrations.AlterField(
            model_name='user_admin',
            name='creatime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 16, 12, 51, 118004), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user_admin',
            name='password',
            field=models.CharField(max_length=200, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user_admin',
            name='username',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user_admin',
            name='uses',
            field=models.IntegerField(default=0, verbose_name='权限使用次数'),
        ),
        migrations.AlterField(
            model_name='user_cookies',
            name='cookies',
            field=models.CharField(max_length=100000, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='user_cookies',
            name='creatime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 16, 12, 51, 118004), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user_cookies',
            name='state',
            field=models.CharField(max_length=200, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='user_cookies',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
