# Generated by Django 4.2.1 on 2023-06-03 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenapps', '0006_alter_liaotian_creatime_alter_loging_creatime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liaotian',
            name='creatime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 10, 34, 6, 40776), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='liaotian',
            name='uid',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='loging',
            name='creatime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 10, 34, 6, 40776), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='Recentime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 10, 34, 6, 24523), verbose_name='最近登录时间'),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='creatime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 10, 34, 6, 24523), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='purchasetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 10, 34, 6, 24523), verbose_name='购买时间'),
        ),
        migrations.AlterField(
            model_name='user_admin',
            name='Recentime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 10, 34, 6, 40776), verbose_name='最近登录时间'),
        ),
        migrations.AlterField(
            model_name='user_admin',
            name='creatime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 10, 34, 6, 40776), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user_cookies',
            name='creatime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 10, 34, 6, 40776), verbose_name='创建时间'),
        ),
    ]
