# syntax=docker/dockerfile:1
FROM python:3.8
WORKDIR /lite
COPY   . .
RUN pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple some-package
CMD ["python","manage.py","runserver", "0.0.0.0:8000"]
EXPOSE 8000